---
- name: Generate Join Command for Workers on master node
  shell: kubeadm token create --print-join-command
  register: join_command
  run_once: true
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Debug join command
  debug:
    msg: "Join command for worker nodes: {{ join_command.stdout }}"
  when: ansible_host != hostvars['k8s-control'].ansible_host

- name: Join worker nodes to Kubernetes cluster
  command: "{{ join_command.stdout }}"
  when: ansible_host != hostvars['k8s-control'].ansible_host




