---
- name: Run kubeadm init on master node
  command: kubeadm init --pod-network-cidr="{{ kubernetes.pod_network_cidr }}"
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Create Kube Directories for both root and ansible user on master node
  shell: |
    mkdir -p /root/.kube
    mkdir -p /home/{{ ansible_user }}/.kube
    chmod 0755 /root/.kube
    chmod 0755 /home/{{ ansible_user }}/.kube
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Copy Admin.conf to Kube Config on master node for both root and ansible user
  shell: |
    cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    cp -f /etc/kubernetes/admin.conf /root/.kube/config
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Change Ownership of Kubeconfig on master node
  command: sudo chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Install Flannel on master node
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: ansible_host == hostvars['k8s-control'].ansible_host

- name: Wait for control-plane to be ready
  shell: kubectl get nodes | grep 'control-plane' | grep -w 'Ready'
  register: kubectl_output
  until: kubectl_output.rc == 0
  retries: 30
  delay: 10
  when: ansible_host == hostvars['k8s-control'].ansible_host
