---
- name: Disable swap
  shell: swapoff -a

- name: Disable swap in fstab
  shell: sed "-i.bak" '/swap/d' /etc/fstab

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist kernel module loading at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'

- name: Configure sysctl parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl parameters
  command: sysctl --system

- name: Install basic dependencies
  shell: |
    apt-get install -y curl
    apt-get install -y  software-properties-common
    apt-get install -y ca-certificates
    apt-get install -y gnupg
    apt-get install -y apt-transport-https

- name: Add Docker GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repository to APT sources
  ansible.builtin.shell: |
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -sc) stable" | \
    tee /etc/apt/sources.list.d/docker-ce.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install containerd
  command: apt install -y containerd.io

- name: Configure cgroup driver for containerd
  ansible.builtin.shell: |
    [ -d /etc/containerd ] || mkdir /etc/containerd
    containerd config default | tee /etc/containerd/config.toml
    sed -i '/SystemdCgroup/s/false/true/' /etc/containerd/config.toml

- name: Start and enable containerd to run on system boot
  command: systemctl enable --now containerd

- name: Restart containerd
  command: systemctl restart containerd

- name: Install Kubernetes repository GPG signing key
  command: sudo apt install gnupg2 -y

- name: Download and import Kubernetes GPG key
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.k8s_version }}/deb/Release.key | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/k8s.gpg

- name: Add Kubernetes package repository to APT sources
  ansible.builtin.shell: |
    echo "deb https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.k8s_version }}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes


  