---
- name: Update apt cache
  shell: |
    apt-get update

- name: Upgrade system packages
  shell: |
    apt-get upgrade -y --fix-missing

- name: Change hostname
  ansible.builtin.shell: |
    hostnamectl set-hostname {{ hostvars[inventory_hostname].hostname }}

- name: Update /etc/hosts file host addresses
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}"
    line: "{{hostvars[item].ansible_host }} {{ hostvars[item].hostname }}"
  with_items: "{{ groups['all'] }}"