---
- name: Remove any Kubernetes related APT source files (if any)
  shell: |
    rm -f /etc/apt/sources.list.d/*kubernetes* || true

- name: Update apt cache
  shell: |
    apt-get update

- name: Upgrade system packages
  shell: |
    apt-get upgrade -y --fix-missing

- name: Change hostname
  ansible.builtin.shell: |
    hostnamectl set-hostname {{ hostvars[inventory_hostname].hostname }}

- name: Update /etc/hosts file host addresses
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_host }}"
    line: "{{hostvars[item].ansible_host }} {{ hostvars[item].hostname }}"
  with_items: "{{ groups['all'] }}"

- name: Update /etc/hosts file host address
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    state: absent
